                                             12345678901234567890
ren  tsImportTestAKextraField.txt            AKextraField.txt
ren  tsImportTestAKfieldsTooLong.txt         AKfieldsTooLong.txt
ren  tsImportTestAKinvalidDate.txt           AKinvalidDate.txt
ren  tsImportTestAKinvalidTime.txt           AKinvalidTime.txt
ren  tsImportTestAKmissingFirstComma.txt     AKnoFirstComma.txt
ren  tsImportTestAKmissingLastComma.txt      AKnoLastComma.txt
ren  tsImportTestAKmissingMandatories.txt    AKnoMandatories.txt
ren  tsImportTestAKmissingRecord.txt         AKnoRecord.txt
ren  tsImportTestAKok.txt                    AKok.txt
ren  tsImportTestAOextraField.txt            AOextraField.txt
ren  tsImportTestAOfieldsTooLong.txt         AOfieldsTooLong.txt
ren  tsImportTestAOinvalidNumbers.txt        AOinvalidNumbers.txt
ren  tsImportTestAOmissingFirstComma.txt     AOnoFirstComma.txt
ren  tsImportTestAOmissingLastComma.txt      AOnoLastComma.txt
ren  tsImportTestAOmissingRecord.txt         AOnoRecord.txt
ren  tsImportTestAOok.txt     AOok.txt
ren  tsImportTestAQextraField.txt            AQextraField.txt
ren  tsImportTestAQfieldsTooLong.txt         AQfieldsTooLong.txt
ren  tsImportTestAQinvalidDate.txt           AQinvalidDate.txt
ren  tsImportTestAQinvalidNumbers.txt        AQinvalidNumbers.txt
ren  tsImportTestAQmissingFinalComma.txt     AQnoFinalComma.txt
ren  tsImportTestAQmissingFirstComma.txt     AQnoFirstComma.txt
ren  tsImportTestAQmissingRecord.txt         AQnoRecord.txt
ren  tsImportTestAQok.txt                    AQok.txt
ren  tsImportTestGKduplicateRecords.txt      GKduplicateRecords.txt
ren  tsImportTestGKextraFields.txt           GKextraFields.txt
ren  tsImportTestGKfiledsTooLong.txt         GKfiledsTooLong.txt
ren  tsImportTestGKmissingFields.txt         GKnoFields.txt
ren  tsImportTestGKmissingMandatories.txt    GKnoMandatories.txt
ren  tsImportTestGKok.txt                    GKok.txt
ren  tsImportTestGKoutOfSequence.txt         GKoutOfSequence.txt
ren  tsImportTestSDextraComma.txt            SDextraComma.txt
ren  tsImportTestSDfieldsTooLong.txt         SDfieldsTooLong.txt
ren  tsImportTestSDinvalidDate.txt           SDinvalidDate.txt
ren  tsImportTestSDmissingFirstComma.txt     SDnoFirstComma.txt
ren  tsImportTestSDmissingLastComma.txt      SDnoLastComma.txt
ren  tsImportTestSDmissingRecord.txt         SDnoRecord.txt
ren  tsImportTestSDok.txt                    SDok.txt
ren  tsImportTestSKextraField.txt            SKextraField.txt
ren  tsImportTestSKfieldsTooLong.txt         SKfieldsTooLong.txt
ren  tsImportTestSKinvalidDate.txt           SKinvalidDate.txt
ren  tsImportTestSKinvalidGroundHeight.txt   SKinvalidGrndHt.txt
ren  tsImportTestSKinvalidLatitude.txt       SKinvalidLatit.txt
ren  tsImportTestSKinvalidLongitude.txt      SKinvalidLongit.txt
ren  tsImportTestSKinvalidTime.txt           SKinvalidTime.txt
ren  tsImportTestSKmissingMandatories.txt    SKnoMandatories.txt
ren  tsImportTestSKok.txt                    SKok.txt
ren  tsImportTestTTextraComma.txt            TTextraComma.txt
ren  tsImportTestTTfieldsTooLong.txt         TTfieldsTooLong.txt
ren  tsImportTestTTinvalidDate.txt           TTinvalidDate.txt
ren  tsImportTestTTinvalidTime.txt           TTinvalidTime.txt
ren  tsImportTestTTmissingFirstComma.txt     TTnoFirstComma.txt
ren  tsImportTestTTmissingLastComma.txt      TTnoLastComma.txt
ren  tsImportTestTTmissingRecord.txt         TTnoRecord.txt
ren  tsImportTestTTok.txt                    TTok.txt