* TS-PDF: aunkn34, By FtPrint (190122-1739/64-R) at 2020.09.14 16:09:58
*
*TT, validated, namef, source, descr, mdate, mtime
TT,U,AUNKN34,FRSE,GENERATED BY AREA COORDINATION,,
*##############################################################################
*SK, cmd, recstat, call1, name, latit, longit, grnd, mdate, mtime:
SK,A,U,AH34,SECTORTEST,50-00-00.00N,085-00-00.00W,200.0, ,
*SD, prov, oper, stats, loc, icaccount, reg, snumb, notwr, nots, spoint, sdate, oprtyp:
SD,ON,UNKN,5, , , , ,1, , , ,UT
*====  ------ Not Found -----   Ant Gain = 15.0, Dist Loss = 54.03, At. Loss = 1.58
*AK, cmd, recstat, call1, call2, bndcde, anum, mdate, mtime:
AK, A,U,AH34,AR34,39A,1, ,
*AQ, ause, acode, aht, azmth, elvtn, dist, offazm, tazmth, telvtn, tgain, obsloss, kvalue, atwrno, sdate:
AQ,TR,TA-14042-120,10.0,180.00,0.00,12.00,N, , , , , , ,
*AO, txfdlnth, txfdlnlh, txfdlntv, txfdlnlv, txpadpam, txcompl, rxfdlnth, rxfdlnlh, rxfdlntv, rxfdlnlv, rxpadlna, rxcompl, nota, apoint, licence:
AO, , , , , , , , , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.74, Rx=91.75
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,1, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38625000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38675000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-95.9, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.94, Rx=91.95
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,10, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39525000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39575000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.96, Rx=91.97
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,11, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39625000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39675000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.98, Rx=91.99
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,12, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39725000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39775000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.00, Rx=92.01
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,13, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39825000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39875000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.02, Rx=92.04
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,14, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39925000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39975000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.76, Rx=91.77
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,2, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38725000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38775000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.78, Rx=91.79
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,3, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38825000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38875000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.80, Rx=91.82
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,4, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38925000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38975000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.83, Rx=91.84
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,5, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39025000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39075000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.85, Rx=91.86
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,6, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39125000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39175000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.87, Rx=91.88
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,7, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39225000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39275000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.89, Rx=91.90
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,8, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39325000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39375000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.92, Rx=91.93
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AH34,AR34,39A,9, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39425000.00,B,1,0.0, , ,MSTAR384, ,35.0, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39475000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-96.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*##############################################################################
*SK, cmd, recstat, call1, name, latit, longit, grnd, mdate, mtime:
SK,A,U,AR34,SECTORTEST,49-53-59.76N,085-00-00.00W,200.0, ,
*SD, prov, oper, stats, loc, icaccount, reg, snumb, notwr, nots, spoint, sdate, oprtyp:
SD,ON,UNKN,5, , , , ,1, , , ,UT
*====  ------ Not Found -----   Ant Gain = 0.0, Dist Loss = 54.03, At. Loss = 1.58
*AK, cmd, recstat, call1, call2, bndcde, anum, mdate, mtime:
AK, A,U,AR34,AH34,39A,1, ,
*AQ, ause, acode, aht, azmth, elvtn, dist, offazm, tazmth, telvtn, tgain, obsloss, kvalue, atwrno, sdate:
AQ,TR,OMNI,5.0,0.00,0.00,12.00,N, , , , , , ,
*AO, txfdlnth, txfdlnlh, txfdlntv, txfdlnlv, txpadpam, txcompl, rxfdlnth, rxfdlnlh, rxfdlntv, rxfdlnlv, rxpadlna, rxcompl, nota, apoint, licence:
AO, , , , , , , , , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.75, Rx=91.74
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,1, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38675000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38625000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-81.9, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.95, Rx=91.94
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,10, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39575000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39525000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.97, Rx=91.96
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,11, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39675000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39625000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.99, Rx=91.98
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,12, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39775000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39725000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.01, Rx=92.00
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,13, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39875000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39825000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.04, Rx=92.02
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,14, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39975000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39925000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.77, Rx=91.76
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,2, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38775000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38725000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.79, Rx=91.78
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,3, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38875000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38825000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.82, Rx=91.80
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,4, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38975000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38925000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.84, Rx=91.83
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,5, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39075000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39025000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.0, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.86, Rx=91.85
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,6, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39175000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39125000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.88, Rx=91.87
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,7, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39275000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39225000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.90, Rx=91.89
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,8, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39375000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39325000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.93, Rx=91.92
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AR34,AH34,39A,9, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39475000.00,B,1,0.0, , ,MSTAR384, ,36.3, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39425000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-82.1, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
