SET pathToExe=D:\Users\ahulme\FCSAwinNew\_build\x64\Release
SET testOutputFile=D:\Users\Ahulme\temp\CALL_500_TestOutput_NATIVE.dat
DEL %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFB968  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFC226  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFD227  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFD989  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFE534  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFG433  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFG496  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFG673  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFH524  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFJ360  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFJ362  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFJ375  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFJ387  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFO860  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFP215  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFP756  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFP939  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFQ373  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFQ468  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFV982  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW267  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW270  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW280  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW342  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW347  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW574  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFW903  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CFY591  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGB207  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGC555  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGD933  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGE497  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGE548  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGE647  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGE828  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGF233  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGF813  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGG593  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGJ394  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGK339  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGM293  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGM348  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGM629  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGP648  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGP649  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGS467  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGS546  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGS578  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGS579  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGU569  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGU741  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGV291  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGV812  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGV958  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY216  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY306  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY316  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY321  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY367  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY623  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CGY940  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHB364  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHF46  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG408  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG409  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG438  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG445  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG521  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHG654  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHK619  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHK620  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHL482  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHL535  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHL683  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHL825  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHL867  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHX361  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHX421  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHX818  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHX820  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CHX822  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CII504  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CII518  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CII528  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIJ346  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIJ906  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIJ918  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIM747  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIN206  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIN308  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIN704  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIN836  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIN837  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIO229  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIO593  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIO714  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CIO992  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CJL811  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CJS666  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CJX732  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CJY71  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CJZ461  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKA212  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKG674  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKG780  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKG964  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKG972  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKJ233  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKJ703  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKJ748  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKJ801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKO458  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT292  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT293  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT716  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT933  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT962  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKT963  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKY299  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKY301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKY610  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKY935  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CKY938  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CYQ535  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CYR844  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CYS387  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CYZ224  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CZL359  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CZL445  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  CZW437  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KBM5602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KBM9302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KCB8803  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KCE4502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KEF9301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KEF9302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KEH5701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KEH5702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KEK6702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KGN5901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KGN5902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KHC9502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KIO2801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KJI6802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KJL7203  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KLP6201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KLP6202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KOB3908  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KOE9007  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KOJ9504  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KPE3001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KPV3203  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KPV3401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KQC5302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KQH6603  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KQO3701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KQO3702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KRG2501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KSX6602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KTI3402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KTI3403  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KTI3501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KXU3908  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KXW7101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KYP2202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KZB5802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KZG2702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  KZX4903  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGAZHA1  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGFOR13  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGFORZ1  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGFORZ8  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGLAZA1  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGMAZF2  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGOG018  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGOOOZ  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  PPTGPIZA3  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VAF215  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VAF250  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VAF283  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VAF360  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VAQ805  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBB547  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBB707  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBB831  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBB938  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBI708  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBK641  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBL953  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBM811  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBM842  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBQ905  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBU531  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBW797  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBW938  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBY679  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBY681  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBY690  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBY691  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VBY963  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VCA351  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VCU580  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VDJ924  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VDP585  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VDS250  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VDY301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEA853  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEB482  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL204  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL558  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL672  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL807  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL838  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEL876  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM266  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM392  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM567  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM623  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM779  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM830  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEM831  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VES801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VET540  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VET541  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VET546  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VET805  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VEZ346  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFE774  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFE950  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF358  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF418  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF425  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF837  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF912  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFF999  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG286  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG493  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG589  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG668  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG680  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG696  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VFG701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VGN882  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VGP214  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VX9FHL  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VX9GKJ  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VX9GKK  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VX9GKL  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VX9GKM  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VXJ212  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VXJ267  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VXJ527  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VXJ702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VXJ731  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYA671  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYA814  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYA950  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYB348  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYB477  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYB510  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYC215  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYC357  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYC360  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYC747  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYD412  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  VYD566  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAA71804  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAB31902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAC21502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAC28201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAH39201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAH39203  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAH39301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAH39302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAH62806  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAK24014  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAL39504  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ39801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ39802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ41801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ41802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ70502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAQ70601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAS44303  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAT98901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAT99202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAY67201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WAY67202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBC98701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBG58701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBK22201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBM61803  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBQ2205  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBS31101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBS31102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WBS38602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCD98301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCD98302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCG33102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCQ46002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCT71002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCT71201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCX42601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCX51201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCX51202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCX63101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WCX63102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WDD71802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WDQ2402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WDQ25  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WDQ2501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WED35801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WEE704  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WEE70401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WEF63201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WEZF  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WFD48601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGR79101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGV67602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGW99902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGX27001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGX27002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGX77212  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGY34004  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGY37804  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGZ51402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGZ57601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGZ60302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WGZ67501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHA7001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHA7002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHA98801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHA98802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHB53801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHB62101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHB62102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHB68601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHC50701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHC89204  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHC89302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHD94002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHF30501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHG32302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHG40302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHI64702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHJ96202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHN28901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHN28902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHN33502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHQ42301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS25001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS25701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS25702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS27001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS27002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS41601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS45402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS48001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS48002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS62002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS62802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS65101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHS65102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY25001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY26401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY26402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY35102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY71102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY77401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WHY89302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA25603  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA25901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA26003  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA26204  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA26704  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIA93703  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WIR2105  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLB94201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLC87402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD29801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD33502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD49302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD57901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD65901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD65902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD84901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD84902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLD97601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE30901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE30902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE37901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE62401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE62402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE63601  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLE63602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF21201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF21202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF39802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF46902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF47002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF61801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF61802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF81401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLF84501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLG56401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLG69502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLG81502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI20102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI36801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI57902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI58101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI58102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI59301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI59302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLI95701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ41001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ54901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ54902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ57301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ81401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLJ81402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLK66901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLK67002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLL36202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLL90503  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLM23301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLM23403  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO28002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO29502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO43701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO43702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO65001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO67201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO71201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLO73602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP38902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP39001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP39002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP43702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP70702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP86201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLP99702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLQ22301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLQ22402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WLV29605  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WME60302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WME69202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WME75901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WME87701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF20502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF21702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF39401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF75603  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF87901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF87902  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMF93402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG23501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG23602  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG54102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG54202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG55701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG55702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG84401  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMG84405  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMJ98402  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMJ98501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMJ98802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMK64905  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM36807  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM84102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM84203  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM90403  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM90502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM91901  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMM92003  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMN52702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMN89404  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMQ26501  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMQ77604  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMQ77804  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMQ94104  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMR86803  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMS36106  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU30002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU35101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU41101  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU41102  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU52201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU52202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU57202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU66502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU69301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU89701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU89702  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU95201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMU95202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMV20202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMV51001  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMV51002  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  CALL  WMV54701  >>  %testOutputFile%
