SET pathToExe=D:\Users\ahulme\FCSAwinNew\_build\x64\Release
SET testOutputFile=D:\Users\Ahulme\temp\LOC_500_TestOutput_NATIVE.dat
DEL %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  5DTVEXPK  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  8JPX  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  8UHX  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  AXM1  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  AXM2  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  AXM3  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  CXM1  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  CXM2  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  CXM3  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  FOX3  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  HFXR  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  HFXT  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  MMX2  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  SXLT  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  T11X  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  TCNX2  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX254  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX255  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX256  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX257  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX258  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX267  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX272  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX300  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX303  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX305  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX306  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX307  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX308  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX309  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX310  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX311  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX312  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX313  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX314  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX315  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX316  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX318  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX319  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX320  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX322  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX323  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX324  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX350  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX356  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX357  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX358  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX359  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX362  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX363  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX364  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX366  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX367  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX369  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX370  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX371  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX372  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX373  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX374  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX375  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX376  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX377  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX388  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX389  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX391  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX392  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX393  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX394  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX395  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX396  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX397  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX398  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX399  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX502  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX510  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX511  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX521  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX522  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX530  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX531  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX532  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX537  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX538  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX539  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX540  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX541  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX542  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX543  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX544  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX549  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX584  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX585  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX586  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX587  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX591  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX592  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX593  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX595  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX596  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX597  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX598  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX604  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX605  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX606  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX607  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX608  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX609  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX612  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX613  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX615  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX616  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX617  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX656  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX660  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX682  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX745  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX747  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX748  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX750  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX751  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX752  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX753  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX754  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX755  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX756  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX765  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX766  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX767  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX768  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX780  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX789  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX790  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX791  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX792  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX845  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX846  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX847  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX848  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX849  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX850  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX851  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX852  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX853  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX854  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX855  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX856  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX857  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX858  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX859  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX860  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX861  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX862  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX863  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX865  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX866  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX867  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX868  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX869  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX870  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX871  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX872  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX873  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX874  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX875  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX876  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX877  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX878  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX879  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX880  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX881  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX882  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX883  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX884  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX964  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9BHR  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9BHS  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9BHT  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVF  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVG  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVH  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVI  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVJ  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVK  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVL  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVM  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVN  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVO  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVP  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVQ  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVR  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVS  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVT  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVU  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVV  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVW  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVX  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVY  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CVZ  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWA  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWB  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWC  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWD  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWE  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWF  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWG  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  VX9CWH  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ200  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ201  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ202  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ203  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ204  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ205  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ206  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ207  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ208  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ209  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ210  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ211  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ212  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ213  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ214  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ215  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ216  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ217  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ218  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ219  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ220  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ221  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ222  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ223  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ224  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ225  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ226  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ227  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ228  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ229  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ230  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ231  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ232  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ233  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ234  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ235  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ236  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ237  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ238  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ239  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ240  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ241  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ242  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ243  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ244  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ245  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ246  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ247  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ248  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ249  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ250  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ251  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ252  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ253  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ254  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ255  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ256  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ257  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ258  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ259  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ260  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ261  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ262  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ263  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ265  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ266  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ267  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ268  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ269  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ270  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ271  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ272  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ273  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ274  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ275  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ276  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ277  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ278  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ279  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ280  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ281  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ282  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ283  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ284  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ285  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ286  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ287  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ288  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ289  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ290  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ291  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ292  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ293  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ294  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ295  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ296  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ297  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ298  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ299  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ300  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ301  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ302  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ303  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ304  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ305  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ306  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ307  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ308  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ309  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ310  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ311  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ348  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ349  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ350  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ351  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ352  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ353  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ354  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ355  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ356  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ357  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ358  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ359  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ360  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ361  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ362  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ363  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ364  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ365  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ366  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ367  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ368  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ369  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ370  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ372  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ373  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ374  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ375  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ376  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ377  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ378  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ379  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ380  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ404  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ405  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ406  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ407  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ408  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ409  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ410  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ411  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ418  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ419  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ420  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ421  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ422  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ423  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ424  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ425  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ426  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ427  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ428  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ429  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ430  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ434  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ435  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ436  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ437  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ438  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ439  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ440  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ441  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ442  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ443  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ445  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ447  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ448  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ449  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ507  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ508  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ515  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ517  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ539  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ540  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ541  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ566  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ700  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ701  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ793  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ795  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ796  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ797  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ800  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ801  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ802  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ803  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ804  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ805  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ806  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ807  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ808  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ809  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ810  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ811  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ812  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ813  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ814  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ815  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ816  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ817  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ818  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ819  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ820  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ821  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ822  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ823  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ824  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ825  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ826  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ827  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ828  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ829  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ830  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ831  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ832  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ833  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ834  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ835  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ836  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ837  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ838  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ839  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ840  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ841  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ842  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ843  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ844  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ845  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ846  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ847  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ848  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ849  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ850  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ852  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ853  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ854  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ855  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ856  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ857  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ858  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ859  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ860  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ861  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ934  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ935  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ936  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ937  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ938  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ939  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ940  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ941  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ942  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ951  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ952  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ953  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ954  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ955  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ956  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ957  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ958  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ959  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ960  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ961  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ962  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ963  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ964  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ965  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ966  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XJ969  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK306  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK543  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK544  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK546  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK547  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK548  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK549  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK591  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK641  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK658  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK659  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK660  >>  %testOutputFile%
%pathToExe%\GetCoords  fcsa  hulme1_0  LOC  XK663  >>  %testOutputFile%
