* TS-PDF: aunkn31, By FtPrint (190122-1739/64-R) at 2020.09.14 16:09:53
*
*TT, validated, namef, source, descr, mdate, mtime
TT,U,AUNKN31,FRSE,GENERATED BY AREA COORDINATION,,
*##############################################################################
*SK, cmd, recstat, call1, name, latit, longit, grnd, mdate, mtime:
SK,A,U,AP31,ACIRCLE,43-42-27.60N,079-23-40.10W,162.5, ,
*SD, prov, oper, stats, loc, icaccount, reg, snumb, notwr, nots, spoint, sdate, oprtyp:
SD,ON,UNKN,5, , , , ,1, , , ,UT
*====  ------ Not Found -----   Ant Gain = 0.0, Dist Loss = 44.49, At. Loss = 0.53
*AK, cmd, recstat, call1, call2, bndcde, anum, mdate, mtime:
AK, A,U,AP31,AP31,39A,1, ,
*AQ, ause, acode, aht, azmth, elvtn, dist, offazm, tazmth, telvtn, tgain, obsloss, kvalue, atwrno, sdate:
AQ,TR,OMNI,10.0,0.00,0.00,4.00,N, , , , , , ,
*AO, txfdlnth, txfdlnlh, txfdlntv, txfdlnlv, txpadpam, txcompl, rxfdlnth, rxfdlnlh, rxfdlntv, rxfdlnlv, rxpadlna, rxcompl, nota, apoint, licence:
AO, , , , , , , , , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.74, Rx=91.75
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,1, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38620000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38660000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.2, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.90, Rx=91.91
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,10, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39340000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39380000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.91, Rx=91.92
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,11, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39420000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39460000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.93, Rx=91.94
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,12, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39500000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39540000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.95, Rx=91.96
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,13, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39580000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39620000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.97, Rx=91.98
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,14, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39660000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39700000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.5, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.98, Rx=91.99
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,15, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39740000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39780000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.5, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.00, Rx=92.01
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,16, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39820000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39860000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.5, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=92.02, Rx=92.03
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,17, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39900000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39940000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.5, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.75, Rx=91.76
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,2, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38700000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38740000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.77, Rx=91.78
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,3, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38780000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38820000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.79, Rx=91.80
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,4, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38860000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38900000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.81, Rx=91.82
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,5, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,38940000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 38980000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.83, Rx=91.83
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,6, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39020000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39060000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.84, Rx=91.85
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,7, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39100000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39140000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.3, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.86, Rx=91.87
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,8, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39180000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39220000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
*+++++++++++++++++++++++++++++++++++++++++++++ Freq Loss: Tx=91.88, Rx=91.89
*CK, cmd, recstat, call1, call2, bndcde, chid, mdate, mtime:
CK,A,U,AP31,AP31,39A,9, ,
*CT, plan, hl, vh, freqtx, poltx, antnumbtx1, afsltx1, antnumbtx2, afsltx2, eqpttx, eqptutx, pwrtx, atpccde, traftx, srvctx, stattx, feetx:
CT,  , , ,39260000.00,B,1,0.0, , ,MSTAR384, ,28.9, ,DMS384, ,5,X
*CR, freqrx, polrx, antnumbrx1, antnumbrx2, antnumbrx3, eqptrx, eqpturx, trafrx, srvcrx, statrx, feerx:
CR, 39300000.00,B,1, , ,MSTAR384, ,DMS384, ,5,X
*CQ, afslrx1, pwrrx1, afslrx2, pwrrx2, afslrx3, pwrrx3, esint, tsint:
CQ, 0.0,-68.4, , , , , ,
*CO, routnumb, stnnumb, hopnumb, notetx, noterx, noteegn, cpoint, sdate:
CO,  , , , , , , ,
