-- ==================================================================================================
-- OVERVIEW
-- ========
-- This stored procedure replaces the functionality provided by the C# program DailyStorage.exe
-- which was used to initiate the daily accounting of FCSA member's fees.
--
-- TECHNICAL BACKGROUND
-- ====================
-- A detailed description of the functionality provided by DailyStorage.exe is provided
-- in the following Technical Note:
--
--   Title:         "Overview of the existing FCSA Automated Fee Accounting Process".
--   Document:       AH-0052 Fee Accounting Algorithm.docx
--   Author:         Andrew Hulme
--   Version/date:   V1.0, 19-Oct-2022.
--
-- PURPOSE
-- =======
-- The primary purpose of this stored procedure is to populate the table [acct].[fileStorage_temp]
-- with information about the Windows file storage currently being used by member/users to save 
-- their reports generated by previous TSIP runs. This report file storage is itemized down to
-- the size (bytes) of individual files for each operator / micsid / fileName.
--
-- T-SQL SOLUTION
-- ==============
-- T-SQL does not provide any 'out of the box' procedures or functions that would answer the 
-- question "what is the file size and last-modified date for a prescribed network file path?".
-- Consequently, a somewhat ingeneous work-around is implemented in this T-SQL script.
-- T-SQL can:
--            a. cause the execution of prescribed DOS commands within a Windows command shell
--               using XP_CMDSHELL.
--            b. read and/or write text from/to Windows files (although this is non-trivial). 
-- The question posed above can be answered by first causing a DOS DIR command to be executed
-- and its results indirected to a temporary Windows text file.
-- T-SQL is then used to read the contents of this Windows temporary file into an SQL table each
-- line of text being a distinct table record.
-- These table record strings are then parsed to extract substrings that provided the full file,
-- path, file size (bytes) and date last-modified.
-- These values are then used to populate the table [acct].[fileStorage_temp].
--
-- DEPENDENCIES
-- ============
-- Text input/output between T-SQL tables and Windows files and its insertion into a SQL table is
-- is a non-trivial exercise. To keep the present script as short as possible, the T-SQL code
-- required to read and write Windows text files has been encapsulated within a table-valued function
-- and a stored procedure that are called by this script, namely:
--
--      acct.IOreadfileAsTable()             : this table-valued function reads lines of text from 
--                                             a file and inserts them as records in a table.
--      acct.IOwriteStringToFile()           : this stored procedure writes a prescribed text string 
--                                             to a prescribed network file path; two write modes are
--                                             supported: OVERWRITE and APPEND.
-- =====================================================================================================

----------------------------------------------------------------------
-- FCSA members only use the 'fcsa' database on the production server.
----------------------------------------------------------------------
USE [fcsa]

--------------------------------------------------------------
-- Declare all the T-SQL variables that we use in this script.
--------------------------------------------------------------
DECLARE @windowsDomainUserName VARCHAR(256)  -- e.g. 'FCSA\AHulme'
DECLARE @windowsUserName       VARCHAR(256)  -- e.g.      'ahulme'
DECLARE @windowsLogFilePath    VARCHAR(256)  -- e.g. 'd:\extractlogs\jscottDailyStorage.txt'
DECLARE @windowsTempFilePath   VARCHAR(256)  -- e.g. 'd:\extractlogs\tempDailyStorage.txt'
DECLARE @CRLF                  CHAR(2)       -- CR + LF
DECLARE @cmd				   VARCHAR(999)	 -- used to construct T-SQL queries to be executed by XP_CMDSHELL.
DECLARE @message               VARCHAR(MAX)  -- Text string message to be written to log file.
DECLARE @dbName                VARCHAR(128)  -- e.g. 'fcsa'
DECLARE @siteType              VARCHAR(128)  -- e.g. 'wwwroot'
DECLARE @dateYesterday         DATE          -- e.g. 20221108 (yyyymmdd)
DECLARE @clientIPaddress       VARCHAR(15)   -- e.g. '10.1.1.12'
DECLARE @userFilesRootDir      VARCHAR(256)  -- e.g. '\\10.1.1.12\d$\Inetpub\wwwroot\mics\userdirs'
DECLARE @numYesterdayRecords   INT           -- the number of records found with yesterday's date.
DECLARE @logFileWriteMode      BIT           -- 0 for OVERWRITE, 1 for APPEND.

-------------------------------------------------------------------------
-- Prescribe the values of all the required variables.
-------------------------------------------------------------------------
SET @CRLF = CONCAT(CHAR(13), CHAR(10))

SELECT @clientIPaddress = CLIENT_NET_ADDRESS FROM SYS.DM_EXEC_CONNECTIONS WHERE SESSION_ID = @@SPID

SET @windowsDomainUserName = SUSER_NAME()

SET @windowsUserName = LOWER(SUBSTRING(@windowsDomainUserName, CHARINDEX('\', @windowsDomainUserName) + 1, LEN(@windowsDomainUserName) - CHARINDEX('\', @windowsDomainUserName)))

SET @windowsLogFilePath = CONCAT('\\', @clientIPaddress, '\d$\extractlogs\', @windowsUserName, 'DailyStorage.txt')

SET @windowsTempFilePath = CONCAT('\\', @clientIPaddress, '\d$\extractlogs\', @windowsUserName, 'Temp.txt')

SET @dbName = DB_NAME()

SET @siteType = 'wwwroot'

SET @userFilesRootDir = CONCAT('\\', @clientIPaddress, '\d$\Inetpub\', @siteType, '\mics\userdirs')

SET @dateYesterday = CONVERT(VARCHAR(10), DATEADD(day, -1, CAST(GETDATE() AS DATE)), 23) 

-------------------------------
-- Write the log file's header.
-------------------------------
SET @logFileWriteMode = 0   -- delete log file if it already exists then create new.

SET @message = CONCAT('DATABASE:  ', @dbName, @CRLF, 'SITETYPE:  ', @siteType, @CRLF, 'ARGS LEN:  2', @CRLF, 'RUN DATE: null', @CRLF, 'EFF DATE:  ', @dateYesterday, @CRLF)
EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode

SET @logFileWriteMode = 1  -- append to an existing text file.

--------------------------------------------------------------------------------
-- Write the values of the script variables to the log to assist with debugging.
--------------------------------------------------------------------------------
SET @message = @CRLF
SET @message = @message + '@clientIPaddress       = ' + @clientIPaddress + @CRLF
SET @message = @message + '@windowsDomainUserName = ' + @windowsDomainUserName + @CRLF
SET @message = @message + '@windowsUserName       = ' + @windowsUserName + @CRLF
SET @message = @message + '@windowsLogFilePath    = ' + @windowsLogFilePath + @CRLF
SET @message = @message + '@windowsTempFilePath   = ' + @windowsTempFilePath + @CRLF
SET @message = @message + '@dbName                = ' + @dbName + @CRLF
SET @message = @message + '@siteType              = ' + @siteType + @CRLF
SET @message = @message + '@userFilesRootDir      = ' + @userFilesRootDir + @CRLF
SET @message = @message + CONCAT('@dateYesterday         = ', @dateYesterday) + @CRLF + @CRLF
EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode

-------------------------------------------------------------------------------------
-- Check whether the table [acct].[daily_storage]  has any records whose storage_date 
-- is yesterday; if so, exit this T-SQL script.
-------------------------------------------------------------------------------------
SET @numYesterdayRecords = 0
IF OBJECT_ID(N'[acct].[daily_storage]', N'U') IS NOT NULL
	BEGIN
		SELECT @numYesterdayRecords = COUNT(storage_date) 
			FROM [acct].[daily_storage] WHERE storage_date = @dateYesterday GROUP BY storage_date
	END

	IF @numYesterdayRecords > 0 
		BEGIN
			-- Log the fact that table [acct].[daily_storage] already contained entries with yesterday's date.
			SET @message = CONCAT(@CRLF,    'ERROR: table [acct].[daily_storage] already contains entries for yesterday (', @dateYesterday, '),')
			SET @message = CONCAT(@message, @CRLF, '       and so the execution of this script has been terminated.', @CRLF)
			EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode
			-- Exit the script.
			RETURN
		END

-- Table:  [acct].[fileStorage_temp]
-- We need to populate with this table with current file size data.
-- We need this table to be initially empty as it must be populated with only yesterday's data.
-- To be safe, DROP the table if it already exists and then create it.
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON

IF OBJECT_ID(N'[acct].[fileStorage_temp]', N'U') IS NOT NULL DROP TABLE [acct].[fileStorage_temp]

CREATE TABLE [acct].[fileStorage_temp](
	[operator]		[char](8) NOT NULL,
	[micsid]		[char](10) NOT NULL,
	[file_name]		[varchar](128) NOT NULL,
	[storage_date]	[date] NOT NULL,
	[total_space]	[int] NOT NULL,
	[create_time]	[datetime] NOT NULL,
	[project_code]	[char](999) NOT NULL, -- change back to 10
 	CONSTRAINT [PK_new_filestorage_temp] PRIMARY KEY CLUSTERED 
	(
		[operator] ASC,
		[micsid] ASC,
		[file_name] ASC,
		[storage_date] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
	
------------------------------------------------------------------
-- Log the fact that we created a new acct.fileStorage_temp table.
------------------------------------------------------------------
SET @message = CONCAT(@CRLF, 'NOTE: table [acct].[fileStorage_temp] was created.', @CRLF)
EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode

-----------------------------------------------------------------------------------------------------
-- We will get the member's current file paths and file sizes (bytes) by using XP_CMDSHELL to execute
-- a cunning DIR command in a Windows shell. We need to indirect the results of the DOS command to a 
-- temporary Windows file. We will first create an empty Windows file that subsequent DOS commands
-- can append into.
-----------------------------------------------------------------------------------------------------
SET @cmd = '<nul (set/p z=) > ' + @WindowsTempFilePath
EXEC XP_CMDSHELL @cmd, NO_OUTPUT

-------------------------------------------------------------------------------------------------------------------
-- The following DOS 'DIR' command will fill the Windows temporary file with many thousand of lines of text
-- of the general type shown below:
-- 
-- \\10.1.1.46\d$\Inetpub\wwwroot\mics\userdirs\abccom\abccom2\tsip_nh_dragonmtnf2_1.CASEDET 39 02/09/2021 06:10 PM
--
-- To assist with debugging, the DOS DIR command is written to the log file.
-------------------------------------------------------------------------------------------------------------------                                                                                       ^  ^
SET @cmd = 'FOR /f %a in (''DIR ' + @userFilesRootDir + ' /S /B /A:-D'') do echo %~fa %~za %~ta  >> ' + @WindowsTempFilePath
SET @message = CONCAT(@CRLF, 'DOS command:    ', @cmd, @CRLF)
EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode

EXEC XP_CMDSHELL @cmd, NO_OUTPUT

-------------------------------------------------------------------------------------------------------------------
-- Each line contains a file path, a file size (bytes) and the date and time at which the file was last modified.
-- These three string fields are separated by a single space - and this is used to extract them.
-- This is laborious because we the file paths can be different string lengths and we have to first 
-- locate the character index of the spaces within the full line and then convert the file size string
-- to an integer and convert the Windows DateTime to T-SQL DateTime. Also, we need to extract the MICS
-- operator name and MicsID from the file path. We will perform this complex sequence of manoeuvers using
-- several intermediate steps using temporary T-SQL tables.
-------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------- 
-- First create a temporary table whose ultimate purpose is to extract the file paths,
-- file sizes and DateTimes for all of the lines in the Windows temporary file. This
-- temporary table will be used to store all the character indices needed to parse
-- the file path, a file size (bytes) and date and time elements.
--------------------------------------------------------------------------------------- 
IF OBJECT_ID('tempdb..#MyTempTable_1') IS NOT NULL DROP TABLE #MyTempTable_1
CREATE TABLE #MyTempTable_1 (
    line VARCHAR(512) PRIMARY KEY,
	filePath VARCHAR(512) NULL,
	oper VARCHAR(6) NULL,
	micsid VARCHAR(10) NULL,
	fileSizeBytes INT NULL,
	dateLastModified DATETIME NULL,
	fileSizeBytesStr VARCHAR(10) NULL,
	dateLastModifiedStr VARCHAR(50) NULL,
	charIndexStartOperName INT NOT NULL,
	charIndexStartMicsID INT NOT NULL,
	charIndexEndMicsID INT NOT NULL,
	charIndexFirstSpace INT NOT NULL,
	charIndexSecondSpace INT NOT NULL
);

-------------------------------------------------------------------------------------------------------
-- Partially populate #MyTempTable_1 with the lines in the Windows temporary file and calculate
-- the char indexes (positions) that will later be used to extract the desired fields as substrings.
-------------------------------------------------------------------------------------------------------
INSERT INTO #MyTempTable_1
	SELECT 
		T.line,
		NULL, NULL, NULL, NULL, NULL, NULL, NULL,
		CHARINDEX('userdirs', T.line) + 9,
		CHARINDEX('\', T.line, CHARINDEX('userdirs\', T.line) + 9) + 1,
		CHARINDEX('\', T.line, CHARINDEX('\', T.line, CHARINDEX('userdirs', T.line) + 9) + 1) - 1,
		CHARINDEX(' ', T.line), 
		CHARINDEX(' ', T.line, CHARINDEX(' ', T.line) + 1)
	FROM acct.IOreadfileAsTable(@WindowsTempFilePath) AS T

---------------------------------------------------------------------------------------------
-- The directory d$\Inetpub\wwwroot\mics\userdirs\ often contains 'junk' files as well
-- as valid member subdirectories. Only the subdirectories contain MICS oper\micsid\*.* files.
-- We need to delete the 'junk files' in the temporary table to avoid causing T-SQL errors
-- due to invalid substring indexing. Also, delete any records that have illegal 'oper code'
-- lengths or 'micsid lengths.
---------------------------------------------------------------------------------------------
DELETE FROM #MyTempTable_1 
	WHERE  charIndexEndMicsID = 0
		OR charIndexStartMicsID - charIndexStartOperName - 1 > 6
		OR charIndexEndMicsID - charIndexStartMicsID + 1 > 10
		OR LEN(line) - charIndexSecondSpace != 19

-------------------------------------------------------------------------------------------
-- Now use the calculated character positions to extract the substrings for the oper name,
-- micsid, file size and date last modified.
-------------------------------------------------------------------------------------------
UPDATE #MyTempTable_1 
	SET 
		filePath = SUBSTRING(line, 1, charIndexFirstSpace - 1),
		oper = SUBSTRING(line, charIndexStartOperName, charIndexStartMicsID - charIndexStartOperName - 1),
		micsID = SUBSTRING(line, charIndexStartMicsID, charIndexEndMicsID - charIndexStartMicsID + 1),
		fileSizeBytesStr = SUBSTRING(line, charIndexFirstSpace + 1, charIndexSecondSpace - charIndexFirstSpace - 1),
	    dateLastModifiedStr = SUBSTRING(line, charIndexSecondSpace + 1, LEN(line) - charIndexSecondSpace)
	FROM #MyTempTable_1

-----------------------------------------------------------------------------------------
-- Finally, convert the file size string to an integer and the Windows last date modified 
-- string to a T-SQL DateTime.
-----------------------------------------------------------------------------------------
UPDATE #MyTempTable_1 
	SET 
	    fileSizeBytes = CAST (fileSizeBytesStr AS INT),
		dateLastModified = CAST (dateLastModifiedStr AS DATETIME)
	FROM #MyTempTable_1

------------------------------------------------------------------------------------
-- Populate table [acct].[fileStorage_temp] with FCSA 'genuine' member data only.
-- By 'genuine' we mean third-party fee-paying companies not FCSA staff, contractors
-- or any operator codes invented for test purposes.
------------------------------------------------------------------------------------
INSERT INTO [acct].[fileStorage_temp]
	SELECT
			T.oper,
			T.micsid,
			T.filePath,
			@dateYesterday,
			T.fileSizeBytes,
			T.dateLastModified,
			'CATCHALL'
	FROM #MyTempTable_1 AS T
	WHERE T.oper IN (    'ABCCOM', 'ALIANT', 'BCHY', 'BELL', 'BMCE', 'BRAGG', 
						'DND', 'GLW', 'HYONE', 'HYQU', 'MTS', 'NAVI', 'NONO', 
						'NTTEL', 'NWT', 'ONT', 'RCTL', 'SHAW', 'STEL', 'TBAY', 
						'TEKSAV', 'TELS', 'TERAGO', 'TLUSAB', 'TLUSBC','TLUSMC', 
						'TLUSQC', 'VDTR', 'WIREIE', 'XCI', 'ZAYO')

-------------------------------------------------------
-- Write out the file paths, sizes etc to the log file.
-------------------------------------------------------
SET @message = ''
SELECT @message = 
					CASE
						WHEN T.file_name IS NULL THEN CONCAT(@message, @CRLF, LTRIM(RTRIM(D.ultrixid)), ':', LTRIM(RTRIM(D.micsid)), ' ', '0')
						ELSE CONCAT(@message, @CRLF, REPLACE(SUBSTRING(T.file_name, 46, LEN(T.file_name) - 46 + 1), '\', ':'), ' ', T.total_space)
					END
	FROM [adm].[account_details] AS D
	LEFT OUTER JOIN [acct].[fileStorage_temp] AS T ON (D.ultrixid = T.operator) AND (D.micsid = T.micsid)
	WHERE D.ultrixid IN ('ABCCOM', 'ALIANT', 'BCHY', 'BELL', 'BMCE', 'BRAGG', 
						'DND', 'GLW', 'HYONE', 'HYQU', 'MTS', 'NAVI', 'NONO', 
						'NTTEL', 'NWT', 'ONT', 'RCTL', 'SHAW', 'STEL', 'TBAY', 
						'TEKSAV', 'TELS', 'TERAGO', 'TLUSAB', 'TLUSBC','TLUSMC', 
						'TLUSQC', 'VDTR', 'WIREIE', 'XCI', 'ZAYO')

SET @message = CONCAT(@message, @CRLF, @CRLF, 'Accounting capture complete.')

EXECUTE acct.IOwriteStringToFile @message, @windowsLogFilePath, @logFileWriteMode

------------
-- Clean up.
------------
DROP TABLE #MyTempTable_1

---------------------------------------------------------------------------------------
-- Finally, execute the stored procedure [acct].[DailyBilling] with yesterday's date
-- as the an argument; this causes qty. 6 other stored procedures to be executed in the
-- following order:
--                    1.     [acct].[CalcDbStorageDaily]
--                    2.     [acct].[SumStoragedaily]
--                    3.     [acct].[SumProgsDaily]
--                    4.     [acct].[FeeCalcTS]
--                    5.     [acct].[FeeCalcES]
--                    6.     [acct].[UpdateRunCount]
-- When executed in the order defined above, these stored procedures perform all the
-- calculations and accumulations required to update FCSA's billing on a daily basis.
---------------------------------------------------------------------------------------
EXEC [acct].[DailyBilling] @dateYesterday

/*
_____ _            _____           _ 
|_   _| |__   ___  | ____|_ __   __| |
  | | | '_ \ / _ \ |  _| | '_ \ / _` |
  | | | | | |  __/ | |___| | | | (_| |
  |_| |_| |_|\___| |_____|_| |_|\__,_|

*/

-- Useful queries for debugging.
/*
SELECT * INTO [acct].[daily_storage] FROM fcsaSQL3.fcsa.acct.daily_storage

SELECT * FROM [acct].[daily_storage] ORDER BY storage_date DESC, operator, micsid, project_code

DELETE FROM [acct].[daily_storage] WHERE storage_date = DATEADD(day, -1, CAST(GETDATE() AS DATE))

SELECT * FROM [acct].[fileStorage_temp]
SELECT * FROM acct.dbstorage_temp WHERE table_name = 'FILES' ORDER BY storage_date DESC, operator, micsid 

--- load file storage summarized by date, operator, micsid
DECLARE @storage_date DATE = '2022-12-27'

INSERT INTO [acct].[dbstorage_temp] 
	(operator, table_name, record_length, storage_date, micsid, project_code, row_count, tabletype, billingtype, short_name, create_time)
	SELECT operator, 'FILES', 1, @storage_date, micsid, 'CATCHALL', sum(total_space), -1, 98, 'FILES', GETDATE()
	FROM [acct].[filestorage_temp] 
	WHERE storage_date = @storage_date
	GROUP BY operator, micsid 

SELECT * FROM [acct].[daily_storage] ORDER BY storage_date DESC, operator, micsid, project_code

SELECT * INTO hulme.daily_storage_copy FROM [acct].[daily_storage]

DELETE FROM [acct].[daily_storage]  WHERE storage_date = '2022-12-29'
DELETE FROM [acct].[dbstorage_temp] WHERE storage_date = '2022-12-29'

SELECT * FROM hulme.daily_storage_copy  ORDER BY storage_date DESC, operator, micsid, project_code
*/
