USE [master]
GO
/****** Object:  Database [Regression]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE DATABASE [Regression]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Regression', FILENAME = N'D:\MSSQL\Data\Regression.mdf' , SIZE = 102400KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Regression_log', FILENAME = N'E:\MSSQL\Log\Regression_log.ldf' , SIZE = 99904KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Regression] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Regression].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Regression] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Regression] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Regression] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Regression] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Regression] SET ARITHABORT OFF 
GO
ALTER DATABASE [Regression] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Regression] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Regression] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Regression] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Regression] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Regression] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Regression] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Regression] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Regression] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Regression] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Regression] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Regression] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Regression] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Regression] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Regression] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Regression] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Regression] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Regression] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Regression] SET  MULTI_USER 
GO
ALTER DATABASE [Regression] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Regression] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Regression] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Regression] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Regression] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Regression', N'ON'
GO
USE [Regression]
GO
/****** Object:  User [FCSA\AHulme]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE USER [FCSA\AHulme] FOR LOGIN [FCSA\AHulme] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [FCSA\AHulme]
GO
/****** Object:  Schema [adm]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [adm]
GO
/****** Object:  Schema [FtValidate]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [FtValidate]
GO
/****** Object:  Schema [hulme]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [hulme]
GO
/****** Object:  Schema [main]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [main]
GO
/****** Object:  Schema [techdef]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [techdef]
GO
/****** Object:  Schema [tsip]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [tsip]
GO
/****** Object:  Schema [web]    Script Date: 6/16/2023 11:48:28 AM ******/
CREATE SCHEMA [web]
GO
/****** Object:  UserDefinedFunction [dbo].[user_schema]    Script Date: 6/16/2023 11:48:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
