name: AWS Connection Test

on:
  push:
    branches:
      - main  # Triggers when you push to your main branch

permissions:
  id-token: write
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::400485161087:role/GitHubActionsWorkflowRole
          aws-region: ca-central-1  # Change to your bucket's AWS region
          audience: ://amazonaws.com

      - name: Verify AWS Login
        run: aws sts get-caller-identity
